add_newline = false

[git_status]
ahead = "⇡${count}"
diverged = " ⇡${ahead_count} ⇣${behind_count}"
behind = "⇣${count}"
stashed = "*${count} "

[git_branch]
format = "[$branch(:$remote_branch)]($style) "
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[nix_shell]
format = '[$symbol]($style) '
